site_name: Convocação de Remanescentes - Fornecedor
theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.top

nav:
  - Início: index.md
  - 1. Acessando uma contratação: 01-acessando-contratacao.md
  - 2. Manifestando interesse: 02-manifestando-interesse.md
  - 3. Condições do vencedor: 03-condicoes-vencedor.md
  - 4. Negociação de preços: 04-negociacao-precos.md
  - 🖨️ Versão para Impressão: manual-completo.md
